name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: False
          SHOW_LOC_CHART: False
          SHOW_UPDATED_DATE: False
          SHOW_SHORT_INFO: False
